In [27]:
import numpy as np

In [42]:
r = np.array ([1000, 10000, 100000, 1000000])
r

array([   1000,   10000,  100000, 1000000])

In [56]:
voltage_values = np.arange(start= 0, stop= 100, step = 10)
voltage_values.shape

(10,)

In [44]:
voltage_values = voltage_values.reshape(voltage_values.shape[0],1)
voltage_values.shape

(10, 1)

In [80]:
current_measures = voltage_values / r

ValueError: operands could not be broadcast together with shapes (10,) (4,) 

In [81]:
current_measures

array([[0.e+00, 0.e+00, 0.e+00, 0.e+00],
       [1.e-02, 1.e-03, 1.e-04, 1.e-05],
       [2.e-02, 2.e-03, 2.e-04, 2.e-05],
       [3.e-02, 3.e-03, 3.e-04, 3.e-05],
       [4.e-02, 4.e-03, 4.e-04, 4.e-05],
       [5.e-02, 5.e-03, 5.e-04, 5.e-05],
       [6.e-02, 6.e-03, 6.e-04, 6.e-05],
       [7.e-02, 7.e-03, 7.e-04, 7.e-05],
       [8.e-02, 8.e-03, 8.e-04, 8.e-05],
       [9.e-02, 9.e-03, 9.e-04, 9.e-05]])

Cambiar forma de un arreglo numpy **Broadcasting**

In [77]:
a = np.arange(6).reshape((1, 6))

In [78]:
empleados = np.array(['pepe','juan','tom','charlie'])

In [79]:
current_measures[:, empleados == 'pepe']

array([[0.  ],
       [0.01],
       [0.02],
       [0.03],
       [0.04],
       [0.05],
       [0.06],
       [0.07],
       [0.08],
       [0.09]])