In [1]:
import numpy as np

In [14]:
np.array([1.0,2,3]).dtype

dtype('float64')

In [15]:
np.array([1.0,2,3],dtype= np.int32).dtype

dtype('int32')

In [18]:
np.array(['a','b','c']).dtype

dtype('<U1')

In [19]:
np.array(['a','b','c']).astype(np.float64)

ValueError: could not convert string to float: 'a'

In [22]:
np.array([1,2,3]).astype(np.float64)

array([1., 2., 3.])

In [25]:
np.array(['1','2','3']).astype(np.float64).dtype

dtype('float64')

NOTA: 
cuando se quiera trabajar con numeros es mejor que se utilize el numpy y para cadenas de texto es mejor utilizar los pandas

In [32]:
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[0,4,7],[7,2,12]])

In [33]:
arr1 > arr

array([[False,  True,  True],
       [ True, False,  True]])

Propagacion en los arreglos significa que se puede hacer cambios al arreglo por medio de referencias

In [34]:
arrc = arr.copy()

In [36]:
arrc[1] = 5

In [37]:
arrc

array([[1, 2, 3],
       [5, 5, 5]])

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr2d= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr2d[2,1]

8

In [43]:
7*4

28